export const queryKeys = {
  me: ["auth", "me"] as const,
  organization: ["organization", "me"] as const,
  dashboard: (range = "30d") => ["dashboard", "overview", range] as const,
  assets: (params?: Record<string, unknown>) => ["assets", params ?? {}] as const,
  asset: (id: string) => ["assets", id] as const,
  vulnerabilities: (params?: Record<string, unknown>) => ["vulnerabilities", params ?? {}] as const,
  threats: (params?: Record<string, unknown>) => ["threats", params ?? {}] as const,
  controls: (params?: Record<string, unknown>) => ["controls", params ?? {}] as const,
  risks: (params?: Record<string, unknown>) => ["risks", params ?? {}] as const,
  risk: (id: string) => ["risks", id] as const,
  riskSummary: ["risks", "summary"] as const,
  financialSummary: ["financial", "summary"] as const,
  lossDistribution: ["financial", "loss-distribution"] as const,
  investments: ["investments"] as const,
  investmentRecommendations: ["investments", "recommendations"] as const,
  scenarios: ["scenarios"] as const,
  attackPaths: ["attack-paths"] as const,
  incidents: (params?: Record<string, unknown>) => ["incidents", params ?? {}] as const,
  incident: (id: string) => ["incidents", id] as const,
  complianceSummary: ["compliance", "summary"] as const,
  complianceFramework: (framework: string) => ["compliance", framework] as const,
  blockchain: ["blockchain"] as const,
  advisorQuestions: ["advisor", "questions"] as const,
  mlStatus: ["ml", "status"] as const,
  mlSignals: ["ml", "signals"] as const,
  mlPerformance: ["ml", "performance"] as const,
  mlAnomalies: ["ml", "anomalies"] as const,
  mlForecast: ["ml", "forecast"] as const,
  mlIncident: (assetId: string) => ["ml", "incident", assetId] as const,
};
